### PR TITLE
Allow auth. plugin to set auth. failure reason

### PR DESCRIPTION
**Pull request by jvff**
It can set it by writing a single line to an external file whose path is
specified in the plugin environment variable "auth_failure_reason_file".
Only works if plugin does deferred authentication.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/openvpn/2)

### CODE REVIEW

**Comment by faern** [comment]
I don't spot any problems. But this is a code base I'm not familiar with.

---

Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---

*[src/openvpn/ssl.c, line 1352 at r1](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-L9ARRrq-ItkBO56YVzg:-L9ARRrs7Oyf3xTn4oIU:b-ac94ue) ([raw file](https://github.com/mullvad/openvpn/blob/0363415ae169ab7b658427fdc8afcbaa10782095/src/openvpn/ssl.c#L1352)):*
> ```C
> 
> #ifdef MANAGEMENT_DEF_AUTH
>     tls_def_auth_set_client_reason(multi, NULL);
> ```

What does this rename from `man` to `tls` mean?

---

*[src/openvpn/ssl_verify.c, line 977 at r1](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-L9ATE0oAYwgVAcdcaKH:-L9ATE0oAYwgVAcdcaKI:b-kuoyhd) ([raw file](https://github.com/mullvad/openvpn/blob/0363415ae169ab7b658427fdc8afcbaa10782095/src/openvpn/ssl_verify.c#L977)):*
> ```C
>         if (fp)
>         {
>             if (getline(&line, &bytes, fp) < 0)
> ```

Maybe just send `&0` instead of `&bytes`? Or if you don't want it to be a magic number in the code then maybe assign it to a const with uppercase name? I feel like `&0` would work, but I'm not that familiar with C style. With the current code I just interpreted it as an output variable and tried to understand where you used the result.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-:-L9ATufsDf6HafDtiU0I:biekgqt)*

**Comment by jvff** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/openvpn/ssl.c, line 1352 at r1](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-L9ARRrq-ItkBO56YVzg:-L9AVXae7KodO8-AL6jR:bf6umju) ([raw file](https://github.com/mullvad/openvpn/blob/0363415ae169ab7b658427fdc8afcbaa10782095/src/openvpn/ssl.c#L1352)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

What does this rename from `man` to `tls` mean?
</blockquote></details>

`man` was referring to the management channel interface. I renamed it because now it's also being used by the plugin infrastructure, and the "generic" prefix I found used elsewhere for authentication stuff was `tls`.

I'm not 100% sure that this is the proper procedure though.

---

*[src/openvpn/ssl_verify.c, line 977 at r1](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-L9ATE0oAYwgVAcdcaKH:-L9AVsLoBELXBLWkBj9X:bi8m92) ([raw file](https://github.com/mullvad/openvpn/blob/0363415ae169ab7b658427fdc8afcbaa10782095/src/openvpn/ssl_verify.c#L977)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Maybe just send `&0` instead of `&bytes`? Or if you don't want it to be a magic number in the code then maybe assign it to a const with uppercase name? I feel like `&0` would work, but I'm not that familiar with C style. With the current code I just interpreted it as an output variable and tried to understand where you used the result.
</blockquote></details>

I'm not sure I understand your point. I'm sending the address of `bytes` so that its value is overwritten by the number of bytes read.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2)*

**Comment by jvff** [comment]
I'll probably have to rebase this on the latest upstream version before attempting to send this upstream, so I'll start doing that today.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-:-L9AWPMmDfODEu3dFYf2:bif6i1q)*

**Comment by faern** [comment]
Nice! And according to Erik they liked to have contributions discussed on the mailing list. So would be nice if you could send an email to their email list. We should probably describe why we need this feature etc. in order to motivate the change. I can help you write something together, just ping me on slack when you want to do it.

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-:-L9AdXlC-5mS51es9vxH:b-a5o137)*

**Comment by faern** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/openvpn/ssl_verify.c, line 977 at r1](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-L9ATE0oAYwgVAcdcaKH:-L9Eac_k0M3u3tPS4K8Q:bgvcj6e) ([raw file](https://github.com/mullvad/openvpn/blob/0363415ae169ab7b658427fdc8afcbaa10782095/src/openvpn/ssl_verify.c#L977)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I'm not sure I understand your point. I'm sending the address of `bytes` so that its value is overwritten by the number of bytes read.
</blockquote></details>

Hmm. No? Not according to `man getline`.
```c
ssize_t getline(char **lineptr, size_t *n, FILE *stream);
```
The second argument, `n`, is used only as input to indicate how long the first argument array is. The man page says the return value is the number of bytes read: `On success, getline() and getdelim() return the number of characters read`.

And you don't seem to use `bytes` for anything after it has been sent in anyway, right?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2)*

**Comment by faern** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/openvpn/ssl_verify.c, line 977 at r1](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-L9ATE0oAYwgVAcdcaKH:-L9Ebch5-oWaYZs9dzgG:b-mkxeex) ([raw file](https://github.com/mullvad/openvpn/blob/0363415ae169ab7b658427fdc8afcbaa10782095/src/openvpn/ssl_verify.c#L977)):*
The man page says that in order to make `getline` allocate the line buffer for you you should send in `NULL` and `&0`:
>       If *lineptr is set to NULL and *n is set 0 before the call, then getline() will allocate a buffer for  storing  the  line.   This
>       buffer should be freed by the user program even if getline() failed.

And it's this special, internal-allocation, case we want to trigger here I guess.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2)*

**Comment by jvff** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/openvpn/ssl_verify.c, line 977 at r1](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-L9ATE0oAYwgVAcdcaKH:-L9F11_-1KP5JLt55Ih4:bvr3jyt) ([raw file](https://github.com/mullvad/openvpn/blob/0363415ae169ab7b658427fdc8afcbaa10782095/src/openvpn/ssl_verify.c#L977)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

The man page says that in order to make `getline` allocate the line buffer for you you should send in `NULL` and `&0`:
>       If *lineptr is set to NULL and *n is set 0 before the call, then getline() will allocate a buffer for  storing  the  line.   This
>       buffer should be freed by the user program even if getline() failed.

And it's this special, internal-allocation, case we want to trigger here I guess.
</blockquote></details>

I actually did it with a `NULL` value as the second parameter first, but it didn't work. Took me a while to find out why the call was failing, but then I read that the value is updated when necessary (i.e., whenever there's an allocation or reallocation) to reflect the new buffer size. From the man page:

```
In either case, on a successful call, *lineptr and *n will be updated to reflect the buffer address and allocated size respectively. 
```

Not the most intuitive API :/

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2)*

**Comment by faern** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/openvpn/ssl_verify.c, line 977 at r1](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-L9ATE0oAYwgVAcdcaKH:-L9F2F8aAEWwvpezYX0M:b-w3m50p) ([raw file](https://github.com/mullvad/openvpn/blob/0363415ae169ab7b658427fdc8afcbaa10782095/src/openvpn/ssl_verify.c#L977)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I actually did it with a `NULL` value as the second parameter first, but it didn't work. Took me a while to find out why the call was failing, but then I read that the value is updated when necessary (i.e., whenever there's an allocation or reallocation) to reflect the new buffer size. From the man page:

```
In either case, on a successful call, *lineptr and *n will be updated to reflect the buffer address and allocated size respectively. 
```

Not the most intuitive API :/
</blockquote></details>

Yeah, you can't send in `NULL`, but `&0` is correct address pointing to a zero, so that is different. It's mostly that `bytes` is quite an indescriptive name, and we never use it for anything.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2)*

**Comment by jvff** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/openvpn/ssl_verify.c, line 977 at r1](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-L9ATE0oAYwgVAcdcaKH:-L9FE5AZ8_NOlplbsDaW:b3na5n8) ([raw file](https://github.com/mullvad/openvpn/blob/0363415ae169ab7b658427fdc8afcbaa10782095/src/openvpn/ssl_verify.c#L977)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Yeah, you can't send in `NULL`, but `&0` is correct address pointing to a zero, so that is different. It's mostly that `bytes` is quite an indescriptive name, and we never use it for anything.
</blockquote></details>

Makes sense, but the C compiler complained about `&0`:

```
error: lvalue required as unary ‘&’ operand
```

Apparently in C you have to be explicit where the `0` is stored, either as a static variable or a local variable on the stack :/

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2)*

**Comment by faern** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/openvpn/ssl_verify.c, line 977 at r1](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-L9ATE0oAYwgVAcdcaKH:-L9FK15X76wJDrU-ggZ_:bmw9ztv) ([raw file](https://github.com/mullvad/openvpn/blob/0363415ae169ab7b658427fdc8afcbaa10782095/src/openvpn/ssl_verify.c#L977)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

Makes sense, but the C compiler complained about `&0`:

```
error: lvalue required as unary ‘&’ operand
```

Apparently in C you have to be explicit where the `0` is stored, either as a static variable or a local variable on the stack :/
</blockquote></details>

I see. Then keep it as is but name it something more descriptive? Like `line_len`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2)*

**Comment by jvff** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/openvpn/ssl_verify.c, line 977 at r1](https://beta.reviewable.io/reviews/mullvad/openvpn/2#-L9ATE0oAYwgVAcdcaKH:-L9FMYoI7lu5_A49BTPp:b-896fix) ([raw file](https://github.com/mullvad/openvpn/blob/0363415ae169ab7b658427fdc8afcbaa10782095/src/openvpn/ssl_verify.c#L977)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

I see. Then keep it as is but name it something more descriptive? Like `line_len`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2)*

**Comment by faern** [comment]
Reviewed 1 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/mullvad/openvpn/2)*

**Comment by jvff** [comment]
Closed because PR #4 replaces this one.

**Pull request closed without merging**
