### PR TITLE
Send auth. failure reason between server and client plugins

### PR DESCRIPTION
**Pull request by jvff**
This is the port of the changes sent to upstream OpenVPN. This replaces PR #2, so that one should be closed after this PR is merged.

---
This change is [Reviewable](https://reviewable.io/reviews/mullvad/openvpn/4)

### CODE REVIEW

**Comment by faern** [comment]
There is so much of this that would be very hard to review without taking a deep dive into OpenVPN. Which is why it would be really sweet to get it reviewed/merged upstream, so we know someone familiar with OpenVPN has read it and approved of it.

But I can't see anything directly wrong with it, so if you have tested it well I guess we have to go with that.

---

Reviewed 4 of 4 files at r1, 2 of 3 files at r2.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---

*[src/openvpn/push.c, line 77 at r2](https://reviewable.io/reviews/mullvad/openvpn/4#-LCTyEHM1ikVSdsST6vu:-LCTyEHM1ikVSdsST6vv:bkatavb) ([raw file](https://github.com/mullvad/openvpn/blob/24d5892cc71ff2c411913b4c5780d7d2c0f6b4e5/src/openvpn/push.c#L77)):*
> ```C
>         c->sig->signal_text = "auth-failure";
> 
>         if (plugin_defined(c->plugins, OPENVPN_PLUGIN_AUTH_FAILED))
> ```

Should this maybe be guarded behind some `#ifdef ENABLE_PLUGIN`, like how the management stuff is? Since plugin support can be disabled via compile arguments this feature should probably be conditionally compiled in.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/openvpn/4#-:-LCTzw-MCm9bI5-gIIH_:b-qz5ys2)*

**Comment by jvff** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/openvpn/push.c, line 77 at r2](https://reviewable.io/reviews/mullvad/openvpn/4#-LCTyEHM1ikVSdsST6vu:-LCUXsvw-CB6Yb5xCFIO:byu2srq) ([raw file](https://github.com/mullvad/openvpn/blob/24d5892cc71ff2c411913b4c5780d7d2c0f6b4e5/src/openvpn/push.c#L77)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Should this maybe be guarded behind some `#ifdef ENABLE_PLUGIN`, like how the management stuff is? Since plugin support can be disabled via compile arguments this feature should probably be conditionally compiled in.
</blockquote></details>

I went to check this, because I thought that if it was missing it should've failed when building with plugins disabled, but it still compiled successfully. After some digging, it seems that when plugins are disabled, the `plugin_defined` function is implemented as always returning `false`, so that means the `ENABLE_PLUGIN` isn't really necessary.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/openvpn/4)*

**Comment by faern** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/openvpn/push.c, line 77 at r2](https://reviewable.io/reviews/mullvad/openvpn/4#-LCTyEHM1ikVSdsST6vu:-LCVats35zy-yzUyfBG8:b-toydr4) ([raw file](https://github.com/mullvad/openvpn/blob/24d5892cc71ff2c411913b4c5780d7d2c0f6b4e5/src/openvpn/push.c#L77)):*
<details><summary><i>Previously, jvff (Janito Vaqueiro Ferreira Filho) wrote…</i></summary><blockquote>

I went to check this, because I thought that if it was missing it should've failed when building with plugins disabled, but it still compiled successfully. After some digging, it seems that when plugins are disabled, the `plugin_defined` function is implemented as always returning `false`, so that means the `ENABLE_PLUGIN` isn't really necessary.
</blockquote></details>

Depending on how one define necessary I guess. With the `#ifdef` the code will be removed and the binary smaller and simpler. Does not have to do the branching at all at runtime. Like with management, I suppose `if (management)` will always be false when management is disabled even without the conditional compilation in place?

But from searching the code base it seems inconsistent if they guard such parts with `#ifdef` or not, so I'm not sure what the desired solution upstream is.

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/openvpn/4)*

**Comment by faern** [comment]
Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/openvpn/4)*

**Comment by jvff** [comment]
*[src/openvpn/push.c, line 77 at r2](https://reviewable.io/reviews/mullvad/openvpn/4#-LCTyEHM1ikVSdsST6vu:-LCYBP6x8V4wOlb85lEq:byk80ft) ([raw file](https://github.com/mullvad/openvpn/blob/24d5892cc71ff2c411913b4c5780d7d2c0f6b4e5/src/openvpn/push.c#L77)):*
<details><summary><i>Previously, faern (Linus Färnstrand) wrote…</i></summary><blockquote>

Depending on how one define necessary I guess. With the `#ifdef` the code will be removed and the binary smaller and simpler. Does not have to do the branching at all at runtime. Like with management, I suppose `if (management)` will always be false when management is disabled even without the conditional compilation in place?

But from searching the code base it seems inconsistent if they guard such parts with `#ifdef` or not, so I'm not sure what the desired solution upstream is.
</blockquote></details>

In the end the result should be the same, the compiler should just remove the dead code, but it's true that some extra compilation time is needed whereas the preprocessor could just have removed it very early.

I still don't completely understand how OpenVPN configures itself, it seems to be complex. Hopefully someone upstream will give us some feedback :/

---


*Comments from [Reviewable](https://reviewable.io/reviews/mullvad/openvpn/4)*

**Pull request merged**
